---
- name: Get public ip
  ipify_facts:
- debug: 
    msg:
      - "Public ip : {{ipify_public_ip}}"
      - "Hostname: {{ ansible_hostname }}"
      - "Distribution name: {{ ansible_distribution }}"
      - "Distribution version: {{  ansible_distribution_major_version }}"
  register: linux_distribution

- name: Print hostnames with distro name_version
  debug:
     msg:
      - "{{ansible_hostname}}: {{linux_distribution.msg}}"
