apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: k8s
 labels:
   app: nginx
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:latest
       ports:
       - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: k8s
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip
  namespace: k8s
spec:
  type: ClusterIP
  selector:
    app: nginx
  clusterIP: 10.96.1.10
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  
  