apiVersion: batch/v1
kind: Job
metadata:
  name: job-external-port
spec:
  template:
    spec:
      containers:
      - name: job-external-port
        image: curlimages/curl:latest
        command: ['sh', '-c', 'curl  http://10.132.0.3:30001/']
      restartPolicy: OnFailure
