---
- name: Fetch a linux distro name/version
  become: true
  hosts: all
  roles:
    - fetch_linux_distro_name_version
    
- name: Create empty file
  become: true
  hosts: iaas
  roles:
    - create_empty_file
