---
- name: Create an empty file
  become: true
  hosts: iaas
  roles:
    - create_empty_file


- name: Fetch a linux distro name/version
  hosts: all
  become: true
  roles: 
    - fetch_linux_distro_name_version
